function configs = preallocate_configs_1_mod_all

% Create an empty structure

dummy_field = cell(1);

configs = struct(...
    'BatPara', dummy_field, ...
    'BTMS', dummy_field, ...
    'SimPara', dummy_field, ...
    'SysPara', dummy_field, ...
    'SysSpec', dummy_field);