function configs = preallocate_configs_1_mod_all

% Create an empty structure

dummy_field = cell(1);

configs = struct(...
    'SysSpec', dummy_field, ...  
    'BatPara', dummy_field, ...
    'SysPara', dummy_field, ...
    'BTMSPara', dummy_field);

